#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: fae1327
#
Name     : R-phylobase
Version  : 0.8.12
Release  : 47
URL      : https://cran.r-project.org/src/contrib/phylobase_0.8.12.tar.gz
Source0  : https://cran.r-project.org/src/contrib/phylobase_0.8.12.tar.gz
Summary  : Base Package for Phylogenetic Structures and Comparative Data
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-phylobase-lib = %{version}-%{release}
Requires: R-RNeXML
Requires: R-Rcpp
Requires: R-ade4
Requires: R-ape
Requires: R-rncl
BuildRequires : R-RNeXML
BuildRequires : R-Rcpp
BuildRequires : R-ade4
BuildRequires : R-ape
BuildRequires : R-rncl
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
one or more trees and trait data.

%package lib
Summary: lib components for the R-phylobase package.
Group: Libraries

%description lib
lib components for the R-phylobase package.


%prep
%setup -q -n phylobase
pushd ..
cp -a phylobase buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706634764

%install
export SOURCE_DATE_EPOCH=1706634764
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/phylobase/DESCRIPTION
/usr/lib64/R/library/phylobase/INDEX
/usr/lib64/R/library/phylobase/Meta/Rd.rds
/usr/lib64/R/library/phylobase/Meta/data.rds
/usr/lib64/R/library/phylobase/Meta/features.rds
/usr/lib64/R/library/phylobase/Meta/hsearch.rds
/usr/lib64/R/library/phylobase/Meta/links.rds
/usr/lib64/R/library/phylobase/Meta/nsInfo.rds
/usr/lib64/R/library/phylobase/Meta/package.rds
/usr/lib64/R/library/phylobase/Meta/vignette.rds
/usr/lib64/R/library/phylobase/NAMESPACE
/usr/lib64/R/library/phylobase/NEWS.md
/usr/lib64/R/library/phylobase/R/phylobase
/usr/lib64/R/library/phylobase/R/phylobase.rdb
/usr/lib64/R/library/phylobase/R/phylobase.rdx
/usr/lib64/R/library/phylobase/data/Rdata.rdb
/usr/lib64/R/library/phylobase/data/Rdata.rds
/usr/lib64/R/library/phylobase/data/Rdata.rdx
/usr/lib64/R/library/phylobase/doc/index.html
/usr/lib64/R/library/phylobase/doc/phylobase.Rmd
/usr/lib64/R/library/phylobase/doc/phylobase.html
/usr/lib64/R/library/phylobase/help/AnIndex
/usr/lib64/R/library/phylobase/help/aliases.rds
/usr/lib64/R/library/phylobase/help/paths.rds
/usr/lib64/R/library/phylobase/help/phylobase.rdb
/usr/lib64/R/library/phylobase/help/phylobase.rdx
/usr/lib64/R/library/phylobase/html/00Index.html
/usr/lib64/R/library/phylobase/html/R.css
/usr/lib64/R/library/phylobase/nexmlfiles/comp_analysis.xml
/usr/lib64/R/library/phylobase/nexusfiles/ExContData.Rdata
/usr/lib64/R/library/phylobase/nexusfiles/MultiLineTrees.nex
/usr/lib64/R/library/phylobase/nexusfiles/NastyLabels.nex
/usr/lib64/R/library/phylobase/nexusfiles/NastyLabels2.nex
/usr/lib64/R/library/phylobase/nexusfiles/co1.nex
/usr/lib64/R/library/phylobase/nexusfiles/minNex.nex
/usr/lib64/R/library/phylobase/nexusfiles/minSeq.nex
/usr/lib64/R/library/phylobase/nexusfiles/newick.tre
/usr/lib64/R/library/phylobase/nexusfiles/noStateLabels.nex
/usr/lib64/R/library/phylobase/nexusfiles/shorebird_underscore.nex
/usr/lib64/R/library/phylobase/nexusfiles/testSubsetTaxa.nex
/usr/lib64/R/library/phylobase/nexusfiles/test_min.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeRoundingError.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithContinuousData.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithDiscAndContData.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithDiscreteData.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithPolyExcludedData.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithSpecialCharacters.nex
/usr/lib64/R/library/phylobase/nexusfiles/treeWithUnderscoreLabels.nex
/usr/lib64/R/library/phylobase/tests/misctests.R
/usr/lib64/R/library/phylobase/tests/phylo4dtests.R
/usr/lib64/R/library/phylobase/tests/phylosubtest.R
/usr/lib64/R/library/phylobase/tests/phylotorture.R
/usr/lib64/R/library/phylobase/tests/plottest.R
/usr/lib64/R/library/phylobase/tests/roundtrip.R
/usr/lib64/R/library/phylobase/tests/test-all.R
/usr/lib64/R/library/phylobase/tests/testprune.R
/usr/lib64/R/library/phylobase/tests/testthat/test.checkdata.R
/usr/lib64/R/library/phylobase/tests/testthat/test.class-phylo4.R
/usr/lib64/R/library/phylobase/tests/testthat/test.class-phylo4d.R
/usr/lib64/R/library/phylobase/tests/testthat/test.formatData.R
/usr/lib64/R/library/phylobase/tests/testthat/test.methods-oldclasses.R
/usr/lib64/R/library/phylobase/tests/testthat/test.methods-phylo4.R
/usr/lib64/R/library/phylobase/tests/testthat/test.pdata.R
/usr/lib64/R/library/phylobase/tests/testthat/test.phylo4.R
/usr/lib64/R/library/phylobase/tests/testthat/test.phylobase.options.R
/usr/lib64/R/library/phylobase/tests/testthat/test.prune.R
/usr/lib64/R/library/phylobase/tests/testthat/test.readNCL.R
/usr/lib64/R/library/phylobase/tests/testthat/test.setAs-Methods.R
/usr/lib64/R/library/phylobase/tests/testthat/test.subset.R
/usr/lib64/R/library/phylobase/tests/testthat/test.tbind.R
/usr/lib64/R/library/phylobase/tests/testthat/test.treePlot.R
/usr/lib64/R/library/phylobase/tests/testthat/test.treestruc.R
/usr/lib64/R/library/phylobase/tests/testthat/test.treewalk.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/phylobase/libs/phylobase.so
/usr/lib64/R/library/phylobase/libs/phylobase.so.avx2
/usr/lib64/R/library/phylobase/libs/phylobase.so.avx512
